namespace: fruits-app
commonLabels:
  app: fruits-api
  version: v1.0
secretGenerator:
  - name: pgsql-credentials
    literals:
      - username=demo
      - password=pa55Word!
      - database=demodb
      - hostname=postgresql.db.svc
      - port=5432
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - rbac.yaml